//DRIINKSSSS
export const DRINK_LIST_REQUEST = "DRINK_LIST_REQUEST";
export const DRINK_LIST_SUCCESS = "DRINK_LIST_SUCCESS";
export const DRINK_LIST_FAIL = "DRINK_LIST_FAIL";

export const DRINK_DETAILS_REQUEST = "DRINK_DETAILS_REQUEST";
export const DRINK_DETAILS_SUCCESS = "DRINK_DETAILS_SUCCESS";
export const DRINK_DETAILS_FAIL = "DRINK_DETAILS_FAIL";

///FOOOOD
export const FOOD_LIST_REQUEST = "FOOD_LIST_REQUEST";
export const FOOD_LIST_SUCCESS = "FOOD_LIST_SUCCESS";
export const FOOD_LIST_FAIL = "FOOD_LIST_FAIL";

export const FOOD_DETAILS_REQUEST = "FOOD_DETAILS_REQUEST";
export const FOOD_DETAILS_SUCCESS = "FOOD_DETAILS_SUCCESS";
export const FOOD_DETAILS_FAIL = "FOOD_DETAILS_FAIL";

///GIFT
export const GIFT_LIST_REQUEST = "GIFT_LIST_REQUEST";
export const GIFT_LIST_SUCCESS = "GIFT_LIST_SUCCESS";
export const GIFT_LIST_FAIL = "GIFT_LIST_FAIL";

export const GIFT_DETAILS_REQUEST = "GIFT_DETAILS_REQUEST";
export const GIFT_DETAILS_SUCCESS = "GIFT_DETAILS_SUCCESS";
export const GIFT_DETAILS_FAIL = "GIFT_DETAILS_FAIL";

///COURSES
export const COURSES_LIST_REQUEST = "COURSES_LIST_REQUEST";
export const COURSES_LIST_SUCCESS = "COURSES_LIST_SUCCESS";
export const COURSES_LIST_FAIL = "COURSES_LIST_FAIL";

export const COURSES_DETAILS_REQUEST = "COURSES_DETAILS_REQUEST";
export const COURSES_DETAILS_SUCCESS = "COURSES_DETAILS_SUCCESS";
export const COURSES_DETAILS_FAIL = "COURSES_DETAILS_FAIL";


///EQUIPMENT
export const EQUIPMENT_LIST_REQUEST = "EQUIPMENT_LIST_REQUEST";
export const EQUIPMENT_LIST_SUCCESS = "EQUIPMENT_LIST_SUCCESS";
export const EQUIPMENT_LIST_FAIL = "EQUIPMENT_LIST_FAIL";

export const EQUIPMENT_DETAILS_REQUEST = "EQUIPMENT_DETAILS_REQUEST";
export const EQUIPMENT_DETAILS_SUCCESS = "EQUIPMENT_DETAILS_SUCCESS";
export const EQUIPMENT_DETAILS_FAIL = "EQUIPMENT_DETAILS_FAIL";